Traceback (most recent call last):
  File "main.py", line 57, in wrapper
    job_func(*args, **kwargs)
  File "main.py", line 91, in comment_listener
    database_manager.load_comment(comment, db_conn)
  File "/root/Fallout76MarketplaceKarmaBot/database_manager.py", line 163, in load_comment
    process_command_non_mod_user(comment, db_conn)
  File "/root/Fallout76MarketplaceKarmaBot/database_manager.py", line 149, in process_command_non_mod_user
    conversation_checks.checks_for_close_command(comment)
  File "/root/Fallout76MarketplaceKarmaBot/conversation_checks.py", line 28, in checks_for_close_command
    flair_functions.close_post_trade(comment)
  File "/root/Fallout76MarketplaceKarmaBot/flair_functions.py", line 143, in close_post_trade
    submission.flair.select(CONSTANTS.TRADE_ENDED_ID)
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/models/reddit/submission.py", line 76, in select
    self.submission._reddit.post(url, data=data)
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/reddit.py", line 793, in post
    return self._objectify_request(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/reddit.py", line 696, in _objectify_request
    self.request(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/reddit.py", line 885, in request
    return self._core.request(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 266, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 500 HTTP response
