Traceback (most recent call last):
  File "/home/pi/Swimbot/venv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/pi/testingWaitlist/waitlist.py", line 83, in waitlist
    await self.wait_board(ctx.message.channel)
  File "/home/pi/testingWaitlist/waitlist.py", line 467, in wait_board
    for player in self.bot.waitlist:
  File "/home/pi/Swimbot/venv/lib/python3.9/site-packages/tinydb/table.py", line 636, in __iter__
    for doc_id, doc in self._read_table().items():
  File "/home/pi/Swimbot/venv/lib/python3.9/site-packages/tinydb/table.py", line 685, in _read_table
    tables = self._storage.read()
  File "/home/pi/Swimbot/venv/lib/python3.9/site-packages/tinydb/storages.py", line 125, in read
    return json.load(self._handle)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 14 (char 13)
