Traceback (most recent call last):
  File "/opt/traktarr/traktarr.py", line 1698, in <module>
    app()
  File "/opt/traktarr/venv/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/traktarr/venv/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/traktarr/venv/lib/python3.8/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/opt/traktarr/venv/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/traktarr/venv/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/traktarr/traktarr.py", line 52, in app
    cfg = Config(configfile=config, cachefile=cachefile, logfile=logfile).cfg
  File "/opt/traktarr/misc/config.py", line 131, in cfg
    tmp = self.load_config()
  File "/opt/traktarr/misc/config.py", line 168, in load_config
    return AttrConfig(json.load(fp))
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 92 column 31 (char 3985)